### ISSUE TITLE
Board G05 - Ne part pas le test des roues s'il  n'y a pas de module bluetooth

### ISSUE THREAD

**Issue by PhiBabin** [RobocupUlavalEmbedded/RobotMCU#19]
De plus, un des moteurs est mal asservie (probablement une mauvaise lecture de son encodeur)

**Comment by PhiBabin** [comment]
Tu as tu testé si c'était fix?

**Comment by TwistedSim** [comment]
Cest pas très important pour le moment et cest plus une task  pour le repo task
