### ISSUE TITLE
le robot se met a spin insanely si la commande d'angle est trop grande

### ISSUE THREAD

**Issue by wonwon0** [RobocupUlavalEmbedded/RobotMCU#28]
Il faut que le robot soiit robuste a ca si non on est obliger de give-up un bon motion control.

Le robot doit se faire reset si on veut quil arrete de spiner. Si on envoie une commande stop le robot arrete de spinner, mais peu importe l'autre commande qu'on envoi apres il recommence a spin.

Si on reset le robot, ca fonctionne meme si l'ia est pas reset aussi.

Dernier test à faire, essayer de reset le robot sans que l'ia perde le robot de vue, ca validerait 100% que le probleme se trouve en embarqué.

J'investique si ca right now.

**Comment by PhiBabin** [comment]
Lorsque tu envoie une commande de stop au robot. Dans le code embarqué le mnrc est reset. Il est donc possible que le mnrc ou un de ses pid accumulé de l'erreur au point où il se met à Spinner peut importe ce qui ce passe. L'autre possibilité est un wrap around a quelque part qui manque. Si tu pouvais printer les commandes envoyé au robot et remarquer c'est quoi le minimum pour reproduire le bug sa serait bien.
